### ISSUE TITLE
/lib/dog.rb in both master and solution branch is empty

### ISSUE THREAD

**Issue by beingy** [learn-co-curriculum/ruby-puppy#4]
Please add solution to dog.rb for reference & refactor pointers.

[https://github.com/learn-co-students/ruby-puppy-v-000/blob/solution/lib/dog.rb](https://github.com/learn-co-students/ruby-puppy-v-000/blob/solution/lib/dog.rb)

**Comment by octosteve** [comment]
@pletcher @AnnJohn I think this just needs to be redeployed. https://github.com/learn-co-curriculum/ruby-puppy/blob/solution/lib/dog.rb has a solution.

**Comment by AnnJohn** [comment]
thanks @StevenNunez will do so
