### ISSUE TITLE
`Dog.all` should be a class reader not a printer.

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ruby-puppy#7]
https://github.com/learn-co-curriculum/ruby-puppy/blob/master/spec/dog_spec.rb#L26-L30

I think `Dog.all` should be a class reader exposing the `@@all` variable. We can have `Dog.print_all` but with this design there is no exposing of a class variable, a class reader, which I believe to be an important concept. It fails to meet the objective - `Write a class method to access the list of all instances of a class, stored in a class variable.`.

I also think that we should be testing `#save` as the method for persisting the instance into `@@all` rather then having them `<<` in initialize directly. Calling `#save` in initialize is fine but it provides more granular testing ability and control from the student.

**Comment by aviflombaum** [comment]
@curiositypaths I'd like to pair with you on re-writing this lab next week.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#8.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hey @aviflombaum,

This lab has been updated based on your feedback - The `.all` method now returns `@@all`, an additional `print_all` method has been added using the previous implementation of `.all`, and `.save` method has been added. The lesson, specs and solution have been updated to reflect these changes.
