### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/ruby-puppy#8]
PROBLEM: Update lessons with guidance that more consistent with the rest of our curriculum. See issue #7.
NOTIFY: @aviflombaum

**Comment by maxwellbenton** [comment]
Updated `.all` to work like other lab examples (now returns `@@all`). Moved existing `.all` implementation to a `print_all` method. Included a `save` method to replace pushing self into `@@all` directly in the initialize method. Tests and readme have been updated to reflect these changes
